version: '3'

services:
  wise-api:
    container_name: wise-api
    hostname: wise-api
    image: wise-api:latest
    build:
      context: ../api
      dockerfile: wise-api.Dockerfile
    ports:
      - "8080:8080"
  wise-ui:
    container_name: wise-ui
    image: wise-ui:latest
    build:
      context: .
      dockerfile: wise-ui.Dockerfile
    depends_on:
      - wise-api
    ports:
      - "80:80"