/*
* Licensed to the Apache Software Foundation (ASF) under one or more
* contributor license agreements.  See the NOTICE file distributed with
* this work for additional information regarding copyright ownership.
* The ASF licenses this file to You under the Apache License, Version 2.0
* (the "License"); you may not use this file except in compliance with
* the License.  You may obtain a copy of the License at
*
*       http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*
* $Id: file 64488 2006-03-10 17:32:09Z paulo $
*/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.04.14 at 05:18:25 PM ART 
//


package com.wisemapping.xml.vmlmap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://mindmap.com/xml/vmlmap}element">
 *       &lt;sequence>
 *         &lt;element ref="{http://mindmap.com/xml/vmlmap}stroke"/>
 *         &lt;element ref="{http://mindmap.com/xml/vmlmap}fill"/>
 *       &lt;/sequence>
 *       &lt;attribute name="coordsize" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="21600,21600" />
 *       &lt;attribute name="stroked" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" fixed="t" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "stroke",
        "fill"
        })
@XmlRootElement(name = "oval")
public class Oval
        extends Element {

    @XmlElement(required = true)
    protected Stroke stroke;
    @XmlElement(required = true)
    protected Fill fill;
    @XmlAttribute(required = true)
    protected String coordsize;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String stroked;

    /**
     * Gets the value of the stroke property.
     *
     * @return possible object is
     *         {@link Stroke }
     */
    public Stroke getStroke() {
        return stroke;
    }

    /**
     * Sets the value of the stroke property.
     *
     * @param value allowed object is
     *              {@link Stroke }
     */
    public void setStroke(Stroke value) {
        this.stroke = value;
    }

    /**
     * Gets the value of the fill property.
     *
     * @return possible object is
     *         {@link Fill }
     */
    public Fill getFill() {
        return fill;
    }

    /**
     * Sets the value of the fill property.
     *
     * @param value allowed object is
     *              {@link Fill }
     */
    public void setFill(Fill value) {
        this.fill = value;
    }

    /**
     * Gets the value of the coordsize property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getCoordsize() {
        if (coordsize == null) {
            return "21600,21600";
        } else {
            return coordsize;
        }
    }

    /**
     * Sets the value of the coordsize property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCoordsize(String value) {
        this.coordsize = value;
    }

    /**
     * Gets the value of the stroked property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getStroked() {
        if (stroked == null) {
            return "t";
        } else {
            return stroked;
        }
    }

    /**
     * Sets the value of the stroked property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStroked(String value) {
        this.stroked = value;
    }

}
