/*
* Licensed to the Apache Software Foundation (ASF) under one or more
* contributor license agreements.  See the NOTICE file distributed with
* this work for additional information regarding copyright ownership.
* The ASF licenses this file to You under the Apache License, Version 2.0
* (the "License"); you may not use this file except in compliance with
* the License.  You may obtain a copy of the License at
*
*       http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*
* $Id: file 64488 2006-03-10 17:32:09Z paulo $
*/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.04.14 at 05:18:25 PM ART 
//


package com.wisemapping.xml.vmlmap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://mindmap.com/xml/vmlmap}element">
 *       &lt;sequence>
 *         &lt;element name="SPAN">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SPAN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="inset" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="0,0,0,0" />
 *       &lt;attribute name="xFontScale" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="xTextSize" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "span"
        })
@XmlRootElement(name = "textbox")
public class Textbox
        extends Element {

    @XmlElement(name = "SPAN", namespace = "", required = true)
    protected Textbox.SPAN span;
    @XmlAttribute(required = true)
    protected String inset;
    @XmlAttribute(required = true)
    protected float xFontScale;
    @XmlAttribute(required = true)
    protected String xTextSize;

    /**
     * Gets the value of the span property.
     *
     * @return possible object is
     *         {@link Textbox.SPAN }
     */
    public Textbox.SPAN getSPAN() {
        return span;
    }

    /**
     * Sets the value of the span property.
     *
     * @param value allowed object is
     *              {@link Textbox.SPAN }
     */
    public void setSPAN(Textbox.SPAN value) {
        this.span = value;
    }

    /**
     * Gets the value of the inset property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getInset() {
        if (inset == null) {
            return "0,0,0,0";
        } else {
            return inset;
        }
    }

    /**
     * Sets the value of the inset property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setInset(String value) {
        this.inset = value;
    }

    /**
     * Gets the value of the xFontScale property.
     */
    public float getXFontScale() {
        return xFontScale;
    }

    /**
     * Sets the value of the xFontScale property.
     */
    public void setXFontScale(float value) {
        this.xFontScale = value;
    }

    /**
     * Gets the value of the xTextSize property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getXTextSize() {
        return xTextSize;
    }

    /**
     * Sets the value of the xTextSize property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setXTextSize(String value) {
        this.xTextSize = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SPAN" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "span"
            })
    public static class SPAN {

        @XmlElement(name = "SPAN", namespace = "", required = true)
        protected String span;

        /**
         * Gets the value of the span property.
         *
         * @return possible object is
         *         {@link String }
         */
        public String getSPAN() {
            return span;
        }

        /**
         * Sets the value of the span property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setSPAN(String value) {
            this.span = value;
        }

    }

}
