spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/wisemapping
    username: wisemapping
    password: password
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      data-source-properties:
        prepareThreshold: 0
        # PostgreSQL uses prepared statements by default, prepareThreshold=0 
        # means always use prepared statements (cached automatically)
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      platform: postgresql
      mode: always
      schema-locations: classpath:schema-postgresql.sql
      data-locations: classpath:data-postgresql.sql
      continue-on-error: false

