DROP TABLE TAG;
DROP TABLE MINDMAP_COLLABORATOR_PROPERTIES;
DROP TABLE MINDMAP_COLABORATOR;
DROP TABLE MINDMAP_HISTORY;
DROP TABLE MINDMAP;
DROP TABLE USER;
DROP TABLE COLABORATOR;
DROP TABLE USER_LOGIN;
COMMIT;