name: Docker Publish

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: jar-artifact
          path: wise-api/target/

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com
          username: doctl
          password: ${{ secrets.DOCR_ACCESS_TOKEN }}

      - name: Build the Docker image
        run: docker buildx build --platform linux/amd64 --build-arg ENABLE_NEWRELIC=true -t wisemapping/wisemapping-api:${{ inputs.tag }} -f distribution/api/wise-api.Dockerfile distribution/api

      - name: Tag Docker image
        run: docker tag wisemapping/wisemapping-api:${{ inputs.tag }} registry.digitalocean.com/wise-registry/wisemapping/wisemapping-api:${{ inputs.tag }}

      - name: Push Image to Repo
        run: docker push registry.digitalocean.com/wise-registry/wisemapping/wisemapping-api:${{ inputs.tag }}